### ISSUE TITLE
Box Password?

### ISSUE THREAD

**Issue by sirop** [strahlex/machinekit-vagrant#2]
Hallo.

So I got now jessy running with vagrant from within machinekit-sdk?

But how shall I guess the password?

b

**Comment by machinekoder** [comment]
You don't need a password, but it should be `vagrant`.

**Comment by sirop** [comment]
My fault.  
I just have to look at `vagrant up` output:

```
    default: SSH username: vagrant
    default: SSH auth method: private key
```
